### ISSUE TITLE
Pdf is not available

### ISSUE THREAD

**Issue by mrtkp9993** [compgenomr/book#34]
Pdf is not available when I clicked the rightmost icon.

<img width="369" alt="Screen Shot 2020-06-01 at 16 30 15" src="https://user-images.githubusercontent.com/17238910/83413849-2fbecc80-a425-11ea-9d2c-7ad1256b58f6.png">
 

<img width="1440" alt="Screen Shot 2020-06-01 at 16 29 39" src="https://user-images.githubusercontent.com/17238910/83413785-187fdf00-a425-11ea-987d-fb1229f4f013.png">

**Comment by al2na** [comment]
pdf won't be available
