### ISSUE TITLE
Unable to Open in PDF Format

### ISSUE THREAD

**Issue by bentoske** [compgenomr/book#51]
Hello! I'm unable to open this in a PDF format, and instead have to access the book through the web interface. This is fine, but there is a PDF link/icon at the top right of the text, and it takes you to a 404 error.

**Comment by al2na** [comment]
try again

**Comment by bentoske** [comment]
Hello! Looks like the PDF link is gone now - will this always be the case, or will a PDF version eventually be available?

**Comment by al2na** [comment]
PDF will not be available
